### ISSUE TITLE
[newTraining] - system-packages-usage-1-ub18

### ISSUE THREAD

**Issue by 6uhrmittag** [admindojo/admindojo-training#7]
**title**: system-packages-usage-1-ub18

**summary**: Basic package operations on Debian-based distributions(dpkg/apt)

**Training outline**:
- [x] provide VM with added repo. customer added repo but cant install it via apt install x (apt update)
- [ ] install .deb
- [ ] see https://www.linuxsysadmins.com/30-dpkg-commands-to-manage-debian-based-linux-servers/
- [ ] see https://askubuntu.com/questions/40779/how-do-i-install-a-deb-file-via-the-command-line
- [ ] sudo apt-get install ./package.deb
- [x] revert broken changes in config file by reconfiguring package
- [x] remove nano

**Todo**:

- [x] choose name
- [x] create branch
- [x] create empty from training
- [x] create inspec profile
    - [x] task is split in logical control/subtasks
    - [x] duration for each control
- [x] create vagrantfile
- [x] create bootstrap
- [x] create test
- [x] create token
- [x] create training instructions
    - [x] instructions cover all controls/subtasks
- [x] test training
- [x] push training
- [x] define points
- [x] create training at admindojo.org
