### ISSUE TITLE
[newTraining] - troubleshoot-user-basic-1-ub18

### ISSUE THREAD

**Issue by 6uhrmittag** [admindojo/admindojo-training#9]
**title**: troubleshoot-user-basic-1-ub18

**summary**: Basic troubleshooting of user issues

**Training outline**:
- unlock locked account
- change password
- cant read files in directory x

**Todo**:

- [x] choose name
- [x] create branch
- [x] create empty from training
- [ ] create inspec profile
    - [ ] task is split in logical control/subtasks
    - [ ] duration for each control
- [ ] create vagrantfile
- [ ] create bootstrap
- [ ] create test
- [ ] create token
- [ ] create training instructions
    - [ ] instructions cover all controls/subtasks
- [ ] test training
- [ ] push training
- [ ] define points
- [ ] create training at admindojo.org
